version: "3"

services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bazi2021
      - POSTGRES_DB=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  dianslab:
    depends_on:
      - postgres
    image: dianslab.jar
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_DB: postgres
    ports:
      - "9091:9091"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml