version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bazi2021
      - POSTGRES_DB=libraries_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    expose:
      - 5432
    ports:
      - "5432:5432"
  dianslab:
    depends_on:
      - postgres
    image: dockerdemo.jar
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/libraries_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bazi2021
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml